#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
export PATH="$HERE/usr/bin:$PATH"
export PYTHONPATH="$HERE/usr/lib/python3.12/site-packages:$HERE/usr/lib/python3/dist-packages:$PYTHONPATH"
exec "$HERE/usr/bin/bluelatch" "$@"
